### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [tactlessfish/ribbon-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by seasonedfish** [comment]
Thanks, I'm honored! I've added the BSD-2-Clause License. But, I'm curious, why is a license necessary if you're only adding a link to my repo?

**Comment by unixorn** [comment]
There are a lot of people who only want to use software with a license, so I've only been adding themes and plugins with a license so that they can decide whether the license is open enough for their preferences.

Thanks for adding one.
